export type InputType =
  | 'text'
  | 'text-color'
  | 'email'
  | 'password'
  | 'password-login'
  | 'textarea'
  | 'select'
  | 'radio'
  | 'checkbox'
  | 'date'
  | 'date-range'
  | 'list'

export type InputUnderneathDisplay = 'none' | 'all' | 'alert' | 'length'
