export const SIZE_LIST = [
  'unit-1',
  'unit-2',
  'unit-3',
  'unit-4',
  'unit-5',
  'unit-6',
  'unit-7',
  'unit-8',
  'unit-9',
  'unit-10',
  'unit-11',
  'unit-12',
  'unit-13',
  'unit-14',
  'unit-15',
  'unit-16',
  'unit-17',
  'unit-18',
  'unit-19',
  'unit-20',
  'unit-21',
  'unit-22',
  'unit-23',
  'unit-24',
  'unit-25',
  'unit-26',
  'unit-27',
  'unit-28',
  'unit-29',
  'unit-30',
  'unit-31',
  'unit-32',
  'unit-33',
  'unit-34',
  'unit-35',
  'unit-36',
  'unit-37',
  'unit-38',
  'unit-39',
  'unit-40',
] as const

export const COLOR_LIST = ['main', 'highlight', 'error'] as const

export const ICONS = {
  CALENDAR: 'fa-regular fa-calendar',
  CARET_DOWN: 'fa-solid fa-caret-down',
  PASSWORD_RESET: 'fa-solid fa-retweet',
  HAMBURGER: 'fa-solid fa-bars',
  LOADING_COMPASS: 'fa-regular fa-compass',
  PLUS: 'fa-solid fa-plus',
  CROSS: 'fa-solid fa-xmark',
  UP_DOWN: 'fa-solid fa-arrows-up-down',
  ARROW_LEFT: 'fa-solid fa-arrow-left',
} as const
